image: node:22-slim

variables:
  PNPM_HOME: "$CI_PROJECT_DIR/.pnpm-home"

cache:
  paths:
    - .pnpm-home
    - node_modules

pages:
  stage: deploy
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm generate
    - pnpm build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
